/**
 * This class is generated by jOOQ
 */
package asdf;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1752178383;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			asdf.Sequences.CERTIFICATES_CERT_PK_SEQ,
			asdf.Sequences.TRAININGS_EMPLOYEES_TREM_PK_SEQ,
			asdf.Sequences.TRAININGS_TRNG_PK_SEQ,
			asdf.Sequences.TRAININGTYPES_TRTY_PK_SEQ,
			asdf.Sequences.UPDATES_UPDT_PK_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			asdf.tables.Certificates.CERTIFICATES,
			asdf.tables.Employees.EMPLOYEES,
			asdf.tables.Sites.SITES,
			asdf.tables.SitesEmployees.SITES_EMPLOYEES,
			asdf.tables.Trainings.TRAININGS,
			asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES,
			asdf.tables.Trainingtypes.TRAININGTYPES,
			asdf.tables.Updates.UPDATES);
	}
}
