/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepartmentsRecord extends org.jooq.impl.UpdatableRecordImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1537018438;

	/**
	 * Setter for <code>public.departments.dept_pk</code>.
	 */
	public void setDeptPk(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.departments.dept_pk</code>.
	 */
	public java.lang.Integer getDeptPk() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.departments.dept_id</code>.
	 */
	public void setDeptId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.departments.dept_id</code>.
	 */
	public java.lang.String getDeptId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.departments.dept_name</code>.
	 */
	public void setDeptName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.departments.dept_name</code>.
	 */
	public java.lang.String getDeptName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS.DEPT_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS.DEPT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS.DEPT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getDeptPk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDeptId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDeptName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DepartmentsRecord value1(java.lang.Integer value) {
		setDeptPk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DepartmentsRecord value2(java.lang.String value) {
		setDeptId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DepartmentsRecord value3(java.lang.String value) {
		setDeptName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DepartmentsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DepartmentsRecord
	 */
	public DepartmentsRecord() {
		super(org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS);
	}

	/**
	 * Create a detached, initialised DepartmentsRecord
	 */
	public DepartmentsRecord(java.lang.Integer deptPk, java.lang.String deptId, java.lang.String deptName) {
		super(org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS);

		setValue(0, deptPk);
		setValue(1, deptId);
		setValue(2, deptName);
	}
}
