/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitesEmployeesRecord extends org.jooq.impl.TableRecordImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1906157902;

	/**
	 * Setter for <code>public.sites_employees.siem_empl_fk</code>.
	 */
	public void setSiemEmplFk(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.sites_employees.siem_empl_fk</code>.
	 */
	public java.lang.String getSiemEmplFk() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.sites_employees.siem_site_fk</code>.
	 */
	public void setSiemSiteFk(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.sites_employees.siem_site_fk</code>.
	 */
	public java.lang.String getSiemSiteFk() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.sites_employees.siem_updt_fk</code>.
	 */
	public void setSiemUpdtFk(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.sites_employees.siem_updt_fk</code>.
	 */
	public java.lang.Integer getSiemUpdtFk() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES.SIEM_EMPL_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES.SIEM_SITE_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES.SIEM_UPDT_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSiemEmplFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSiemSiteFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSiemUpdtFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesEmployeesRecord value1(java.lang.String value) {
		setSiemEmplFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesEmployeesRecord value2(java.lang.String value) {
		setSiemSiteFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesEmployeesRecord value3(java.lang.Integer value) {
		setSiemUpdtFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesEmployeesRecord values(java.lang.String value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SitesEmployeesRecord
	 */
	public SitesEmployeesRecord() {
		super(org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES);
	}

	/**
	 * Create a detached, initialised SitesEmployeesRecord
	 */
	public SitesEmployeesRecord(java.lang.String siemEmplFk, java.lang.String siemSiteFk, java.lang.Integer siemUpdtFk) {
		super(org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES);

		setValue(0, siemEmplFk);
		setValue(1, siemSiteFk);
		setValue(2, siemUpdtFk);
	}
}
