/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitesRecord extends org.jooq.impl.UpdatableRecordImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -335500253;

	/**
	 * Setter for <code>public.sites.site_pk</code>.
	 */
	public void setSitePk(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.sites.site_pk</code>.
	 */
	public java.lang.String getSitePk() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.sites.site_name</code>.
	 */
	public void setSiteName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.sites.site_name</code>.
	 */
	public java.lang.String getSiteName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.sites.site_dept_fk</code>.
	 */
	public void setSiteDeptFk(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.sites.site_dept_fk</code>.
	 */
	public java.lang.Integer getSiteDeptFk() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES.SITE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES.SITE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES.SITE_DEPT_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSitePk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSiteName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSiteDeptFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord value1(java.lang.String value) {
		setSitePk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord value2(java.lang.String value) {
		setSiteName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord value3(java.lang.Integer value) {
		setSiteDeptFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord values(java.lang.String value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SitesRecord
	 */
	public SitesRecord() {
		super(org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES);
	}

	/**
	 * Create a detached, initialised SitesRecord
	 */
	public SitesRecord(java.lang.String sitePk, java.lang.String siteName, java.lang.Integer siteDeptFk) {
		super(org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES);

		setValue(0, sitePk);
		setValue(1, siteName);
		setValue(2, siteDeptFk);
	}
}
