/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingsRecord extends org.jooq.impl.UpdatableRecordImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord> implements org.jooq.Record4<java.lang.Integer, java.sql.Date, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -1232096187;

	/**
	 * Setter for <code>public.trainings.trng_pk</code>.
	 */
	public void setTrngPk(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.trainings.trng_pk</code>.
	 */
	public java.lang.Integer getTrngPk() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.trainings.trng_date</code>.
	 */
	public void setTrngDate(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.trainings.trng_date</code>.
	 */
	public java.sql.Date getTrngDate() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>public.trainings.trng_trty_fk</code>.
	 */
	public void setTrngTrtyFk(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.trainings.trng_trty_fk</code>.
	 */
	public java.lang.Integer getTrngTrtyFk() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.trainings.trng_outcome</code>.
	 */
	public void setTrngOutcome(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.trainings.trng_outcome</code>.
	 */
	public java.lang.String getTrngOutcome() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.sql.Date, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.sql.Date, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_TRTY_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_OUTCOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTrngPk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getTrngDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTrngTrtyFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTrngOutcome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsRecord value1(java.lang.Integer value) {
		setTrngPk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsRecord value2(java.sql.Date value) {
		setTrngDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsRecord value3(java.lang.Integer value) {
		setTrngTrtyFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsRecord value4(java.lang.String value) {
		setTrngOutcome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsRecord values(java.lang.Integer value1, java.sql.Date value2, java.lang.Integer value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrainingsRecord
	 */
	public TrainingsRecord() {
		super(org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS);
	}

	/**
	 * Create a detached, initialised TrainingsRecord
	 */
	public TrainingsRecord(java.lang.Integer trngPk, java.sql.Date trngDate, java.lang.Integer trngTrtyFk, java.lang.String trngOutcome) {
		super(org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS);

		setValue(0, trngPk);
		setValue(1, trngDate);
		setValue(2, trngTrtyFk);
		setValue(3, trngOutcome);
	}
}
