/**
 * This class is generated by jOOQ
 */
package asdf;

/**
 * A class modelling foreign key relationships between tables of the
 * <code>public</code> schema
 */
@javax.annotation.Generated(
							value = {
									"http://www.jooq.org",
									"jOOQ version:3.5.1"
							},
							comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<asdf.tables.records.CertificatesRecord, java.lang.Integer> IDENTITY_CERTIFICATES = Identities0.IDENTITY_CERTIFICATES;
	public static final org.jooq.Identity<asdf.tables.records.TrainingsRecord, java.lang.Integer> IDENTITY_TRAININGS = Identities0.IDENTITY_TRAININGS;
	public static final org.jooq.Identity<asdf.tables.records.TrainingsEmployeesRecord, java.lang.Integer> IDENTITY_TRAININGS_EMPLOYEES = Identities0.IDENTITY_TRAININGS_EMPLOYEES;
	public static final org.jooq.Identity<asdf.tables.records.TrainingtypesRecord, java.lang.Integer> IDENTITY_TRAININGTYPES = Identities0.IDENTITY_TRAININGTYPES;
	public static final org.jooq.Identity<asdf.tables.records.UpdatesRecord, java.lang.Integer> IDENTITY_UPDATES = Identities0.IDENTITY_UPDATES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<asdf.tables.records.CertificatesRecord> CERT_PK = UniqueKeys0.CERT_PK;
	public static final org.jooq.UniqueKey<asdf.tables.records.EmployeesRecord> EMPL_PK = UniqueKeys0.EMPL_PK;
	public static final org.jooq.UniqueKey<asdf.tables.records.SitesRecord> SITE_PK = UniqueKeys0.SITE_PK;
	public static final org.jooq.UniqueKey<asdf.tables.records.TrainingsRecord> TRNG_PK = UniqueKeys0.TRNG_PK;
	public static final org.jooq.UniqueKey<asdf.tables.records.TrainingsEmployeesRecord> TREM_PK = UniqueKeys0.TREM_PK;
	public static final org.jooq.UniqueKey<asdf.tables.records.TrainingtypesRecord> TRTY_PK = UniqueKeys0.TRTY_PK;
	public static final org.jooq.UniqueKey<asdf.tables.records.UpdatesRecord> UPDT_PK = UniqueKeys0.UPDT_PK;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<asdf.tables.records.TrainingtypesRecord, asdf.tables.records.CertificatesRecord> TRAININGTYPES__TRTY_CERT_FK = ForeignKeys0.TRAININGTYPES__TRTY_CERT_FK;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {

		public static org.jooq.Identity<asdf.tables.records.CertificatesRecord, java.lang.Integer> IDENTITY_CERTIFICATES = createIdentity(
																																			asdf.tables.Certificates.CERTIFICATES,
																																			asdf.tables.Certificates.CERTIFICATES.CERT_PK);
		public static org.jooq.Identity<asdf.tables.records.TrainingsRecord, java.lang.Integer> IDENTITY_TRAININGS = createIdentity(
																																	asdf.tables.Trainings.TRAININGS,
																																	asdf.tables.Trainings.TRAININGS.TRNG_PK);
		public static org.jooq.Identity<asdf.tables.records.TrainingsEmployeesRecord, java.lang.Integer> IDENTITY_TRAININGS_EMPLOYEES = createIdentity(
																																						asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES,
																																						asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_PK);
		public static org.jooq.Identity<asdf.tables.records.TrainingtypesRecord, java.lang.Integer> IDENTITY_TRAININGTYPES = createIdentity(
																																			asdf.tables.Trainingtypes.TRAININGTYPES,
																																			asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_PK);
		public static org.jooq.Identity<asdf.tables.records.UpdatesRecord, java.lang.Integer> IDENTITY_UPDATES = createIdentity(
																																asdf.tables.Updates.UPDATES,
																																asdf.tables.Updates.UPDATES.UPDT_PK);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {

		public static final org.jooq.UniqueKey<asdf.tables.records.CertificatesRecord> CERT_PK = createUniqueKey(
																													asdf.tables.Certificates.CERTIFICATES,
																													asdf.tables.Certificates.CERTIFICATES.CERT_PK);
		public static final org.jooq.UniqueKey<asdf.tables.records.EmployeesRecord> EMPL_PK = createUniqueKey(
																												asdf.tables.Employees.EMPLOYEES,
																												asdf.tables.Employees.EMPLOYEES.EMPL_PK);
		public static final org.jooq.UniqueKey<asdf.tables.records.SitesRecord> SITE_PK = createUniqueKey(
																											asdf.tables.Sites.SITES,
																											asdf.tables.Sites.SITES.SITE_PK);
		public static final org.jooq.UniqueKey<asdf.tables.records.TrainingsRecord> TRNG_PK = createUniqueKey(
																												asdf.tables.Trainings.TRAININGS,
																												asdf.tables.Trainings.TRAININGS.TRNG_PK);
		public static final org.jooq.UniqueKey<asdf.tables.records.TrainingsEmployeesRecord> TREM_PK = createUniqueKey(
																														asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES,
																														asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_PK);
		public static final org.jooq.UniqueKey<asdf.tables.records.TrainingtypesRecord> TRTY_PK = createUniqueKey(
																													asdf.tables.Trainingtypes.TRAININGTYPES,
																													asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_PK);
		public static final org.jooq.UniqueKey<asdf.tables.records.UpdatesRecord> UPDT_PK = createUniqueKey(
																											asdf.tables.Updates.UPDATES,
																											asdf.tables.Updates.UPDATES.UPDT_PK);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {

		public static final org.jooq.ForeignKey<asdf.tables.records.TrainingtypesRecord, asdf.tables.records.CertificatesRecord> TRAININGTYPES__TRTY_CERT_FK = createForeignKey(
																																												asdf.Keys.CERT_PK,
																																												asdf.tables.Trainingtypes.TRAININGTYPES,
																																												asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_CERT_FK);
	}
}
