/**
 * This class is generated by jOOQ
 */
package asdf;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
							value = {
									"http://www.jooq.org",
									"jOOQ version:3.5.1"
							},
							comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all" })
public class Tables {

	/**
	 * The table public.certificates
	 */
	public static final asdf.tables.Certificates CERTIFICATES = asdf.tables.Certificates.CERTIFICATES;

	/**
	 * The table public.employees
	 */
	public static final asdf.tables.Employees EMPLOYEES = asdf.tables.Employees.EMPLOYEES;

	/**
	 * The table public.sites
	 */
	public static final asdf.tables.Sites SITES = asdf.tables.Sites.SITES;

	/**
	 * The table public.sites_employees
	 */
	public static final asdf.tables.SitesEmployees SITES_EMPLOYEES = asdf.tables.SitesEmployees.SITES_EMPLOYEES;

	/**
	 * The table public.trainings
	 */
	public static final asdf.tables.Trainings TRAININGS = asdf.tables.Trainings.TRAININGS;

	/**
	 * The table public.trainings_employees
	 */
	public static final asdf.tables.TrainingsEmployees TRAININGS_EMPLOYEES = asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES;

	/**
	 * The table public.trainingtypes
	 */
	public static final asdf.tables.Trainingtypes TRAININGTYPES = asdf.tables.Trainingtypes.TRAININGTYPES;

	/**
	 * The table public.updates
	 */
	public static final asdf.tables.Updates UPDATES = asdf.tables.Updates.UPDATES;
}
