/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.Integer> IDENTITY_CERTIFICATES = Identities0.IDENTITY_CERTIFICATES;
	public static final org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord, java.lang.Integer> IDENTITY_DEPARTMENTS = Identities0.IDENTITY_DEPARTMENTS;
	public static final org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord, java.lang.Integer> IDENTITY_TRAININGS = Identities0.IDENTITY_TRAININGS;
	public static final org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.Integer> IDENTITY_TRAININGS_EMPLOYEES = Identities0.IDENTITY_TRAININGS_EMPLOYEES;
	public static final org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.Integer> IDENTITY_TRAININGTYPES = Identities0.IDENTITY_TRAININGTYPES;
	public static final org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord, java.lang.Integer> IDENTITY_UPDATES = Identities0.IDENTITY_UPDATES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> CERT_PK = UniqueKeys0.CERT_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> DEPT_PK = UniqueKeys0.DEPT_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.EmployeesRecord> EMPL_PK = UniqueKeys0.EMPL_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> SITE_PK = UniqueKeys0.SITE_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord> TRNG_PK = UniqueKeys0.TRNG_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> TREM_PK = UniqueKeys0.TREM_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> TRTY_PK = UniqueKeys0.TRTY_PK;
	public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> UPDT_PK = UniqueKeys0.UPDT_PK;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> SITES__SITE_DEPT_FK = ForeignKeys0.SITES__SITE_DEPT_FK;
	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.EmployeesRecord> SITES_EMPLOYEES__SIEM_EMPL_FK = ForeignKeys0.SITES_EMPLOYEES__SIEM_EMPL_FK;
	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> SITES_EMPLOYEES__SIEM_SITE_FK = ForeignKeys0.SITES_EMPLOYEES__SIEM_SITE_FK;
	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> SITES_EMPLOYEES__SIEM_UPDT_FK = ForeignKeys0.SITES_EMPLOYEES__SIEM_UPDT_FK;
	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> TRAININGS__TRNG_TRTY_FK = ForeignKeys0.TRAININGS__TRNG_TRTY_FK;
	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord> TRAININGS_EMPLOYEES__TREM_TRNG_FK = ForeignKeys0.TRAININGS_EMPLOYEES__TREM_TRNG_FK;
	public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> TRAININGTYPES__TRTY_CERT_FK = ForeignKeys0.TRAININGTYPES__TRTY_CERT_FK;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.Integer> IDENTITY_CERTIFICATES = createIdentity(org.ccjmne.faomaintenance.api.jooq.tables.Certificates.CERTIFICATES, org.ccjmne.faomaintenance.api.jooq.tables.Certificates.CERTIFICATES.CERT_PK);
		public static org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord, java.lang.Integer> IDENTITY_DEPARTMENTS = createIdentity(org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS, org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS.DEPT_PK);
		public static org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord, java.lang.Integer> IDENTITY_TRAININGS = createIdentity(org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS, org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_PK);
		public static org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.Integer> IDENTITY_TRAININGS_EMPLOYEES = createIdentity(org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_PK);
		public static org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.Integer> IDENTITY_TRAININGTYPES = createIdentity(org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES, org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES.TRTY_PK);
		public static org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord, java.lang.Integer> IDENTITY_UPDATES = createIdentity(org.ccjmne.faomaintenance.api.jooq.tables.Updates.UPDATES, org.ccjmne.faomaintenance.api.jooq.tables.Updates.UPDATES.UPDT_PK);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> CERT_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Certificates.CERTIFICATES, org.ccjmne.faomaintenance.api.jooq.tables.Certificates.CERTIFICATES.CERT_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> DEPT_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS, org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS.DEPT_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.EmployeesRecord> EMPL_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Employees.EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.Employees.EMPLOYEES.EMPL_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> SITE_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES, org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES.SITE_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord> TRNG_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS, org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> TREM_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> TRTY_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES, org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES.TRTY_PK);
		public static final org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> UPDT_PK = createUniqueKey(org.ccjmne.faomaintenance.api.jooq.tables.Updates.UPDATES, org.ccjmne.faomaintenance.api.jooq.tables.Updates.UPDATES.UPDT_PK);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> SITES__SITE_DEPT_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.DEPT_PK, org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES, org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES.SITE_DEPT_FK);
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.EmployeesRecord> SITES_EMPLOYEES__SIEM_EMPL_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.EMPL_PK, org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES.SIEM_EMPL_FK);
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> SITES_EMPLOYEES__SIEM_SITE_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.SITE_PK, org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES.SIEM_SITE_FK);
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> SITES_EMPLOYEES__SIEM_UPDT_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.UPDT_PK, org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES.SIEM_UPDT_FK);
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> TRAININGS__TRNG_TRTY_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.TRTY_PK, org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS, org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS.TRNG_TRTY_FK);
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsRecord> TRAININGS_EMPLOYEES__TREM_TRNG_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.TRNG_PK, org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES, org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_TRNG_FK);
		public static final org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> TRAININGTYPES__TRTY_CERT_FK = createForeignKey(org.ccjmne.faomaintenance.api.jooq.Keys.CERT_PK, org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES, org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES.TRTY_CERT_FK);
	}
}
