/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq;

/**
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.certificates_cert_pk_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> CERTIFICATES_CERT_PK_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("certificates_cert_pk_seq", org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.departments_dept_pk_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> DEPARTMENTS_DEPT_PK_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("departments_dept_pk_seq", org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.trainings_employees_trem_pk_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> TRAININGS_EMPLOYEES_TREM_PK_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("trainings_employees_trem_pk_seq", org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.trainings_trng_pk_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> TRAININGS_TRNG_PK_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("trainings_trng_pk_seq", org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.trainingtypes_trty_pk_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> TRAININGTYPES_TRTY_PK_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("trainingtypes_trty_pk_seq", org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.updates_updt_pk_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> UPDATES_UPDT_PK_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("updates_updt_pk_seq", org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
