/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.certificates
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Certificates CERTIFICATES = org.ccjmne.faomaintenance.api.jooq.tables.Certificates.CERTIFICATES;

	/**
	 * The table public.departments
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Departments DEPARTMENTS = org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS;

	/**
	 * The table public.employees
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Employees EMPLOYEES = org.ccjmne.faomaintenance.api.jooq.tables.Employees.EMPLOYEES;

	/**
	 * The table public.sites
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Sites SITES = org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES;

	/**
	 * The table public.sites_employees
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees SITES_EMPLOYEES = org.ccjmne.faomaintenance.api.jooq.tables.SitesEmployees.SITES_EMPLOYEES;

	/**
	 * The table public.trainings
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Trainings TRAININGS = org.ccjmne.faomaintenance.api.jooq.tables.Trainings.TRAININGS;

	/**
	 * The table public.trainings_employees
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees TRAININGS_EMPLOYEES = org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES;

	/**
	 * The table public.trainingtypes
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes TRAININGTYPES = org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES;

	/**
	 * The table public.updates
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Updates UPDATES = org.ccjmne.faomaintenance.api.jooq.tables.Updates.UPDATES;
}
