/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Certificates extends org.jooq.impl.TableImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> {

	private static final long serialVersionUID = 703662425;

	/**
	 * The reference instance of <code>public.certificates</code>
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Certificates CERTIFICATES = new org.ccjmne.faomaintenance.api.jooq.tables.Certificates();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> getRecordType() {
		return org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord.class;
	}

	/**
	 * The column <code>public.certificates.cert_pk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.Integer> CERT_PK = createField("cert_pk", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.certificates.cert_name</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.String> CERT_NAME = createField("cert_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>public.certificates.cert_target</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.Integer> CERT_TARGET = createField("cert_target", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.certificates.cert_permanentonly</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.Boolean> CERT_PERMANENTONLY = createField("cert_permanentonly", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * Create a <code>public.certificates</code> table reference
	 */
	public Certificates() {
		this("certificates", null);
	}

	/**
	 * Create an aliased <code>public.certificates</code> table reference
	 */
	public Certificates(java.lang.String alias) {
		this(alias, org.ccjmne.faomaintenance.api.jooq.tables.Certificates.CERTIFICATES);
	}

	private Certificates(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Certificates(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord, java.lang.Integer> getIdentity() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.IDENTITY_CERTIFICATES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord> getPrimaryKey() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.CERT_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.CertificatesRecord>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.CERT_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ccjmne.faomaintenance.api.jooq.tables.Certificates as(java.lang.String alias) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Certificates(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ccjmne.faomaintenance.api.jooq.tables.Certificates rename(java.lang.String name) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Certificates(name, null);
	}
}
