/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Departments extends org.jooq.impl.TableImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> {

	private static final long serialVersionUID = 1575048276;

	/**
	 * The reference instance of <code>public.departments</code>
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Departments DEPARTMENTS = new org.ccjmne.faomaintenance.api.jooq.tables.Departments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> getRecordType() {
		return org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord.class;
	}

	/**
	 * The column <code>public.departments.dept_pk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord, java.lang.Integer> DEPT_PK = createField("dept_pk", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.departments.dept_id</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord, java.lang.String> DEPT_ID = createField("dept_id", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "");

	/**
	 * The column <code>public.departments.dept_name</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord, java.lang.String> DEPT_NAME = createField("dept_name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * Create a <code>public.departments</code> table reference
	 */
	public Departments() {
		this("departments", null);
	}

	/**
	 * Create an aliased <code>public.departments</code> table reference
	 */
	public Departments(java.lang.String alias) {
		this(alias, org.ccjmne.faomaintenance.api.jooq.tables.Departments.DEPARTMENTS);
	}

	private Departments(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Departments(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord, java.lang.Integer> getIdentity() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.IDENTITY_DEPARTMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord> getPrimaryKey() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.DEPT_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.DepartmentsRecord>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.DEPT_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ccjmne.faomaintenance.api.jooq.tables.Departments as(java.lang.String alias) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Departments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ccjmne.faomaintenance.api.jooq.tables.Departments rename(java.lang.String name) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Departments(name, null);
	}
}
