/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sites extends org.jooq.impl.TableImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> {

	private static final long serialVersionUID = -1038117576;

	/**
	 * The reference instance of <code>public.sites</code>
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Sites SITES = new org.ccjmne.faomaintenance.api.jooq.tables.Sites();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> getRecordType() {
		return org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord.class;
	}

	/**
	 * The column <code>public.sites.site_pk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, java.lang.String> SITE_PK = createField("site_pk", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>public.sites.site_name</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, java.lang.String> SITE_NAME = createField("site_name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>public.sites.site_dept_fk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, java.lang.Integer> SITE_DEPT_FK = createField("site_dept_fk", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.sites</code> table reference
	 */
	public Sites() {
		this("sites", null);
	}

	/**
	 * Create an aliased <code>public.sites</code> table reference
	 */
	public Sites(java.lang.String alias) {
		this(alias, org.ccjmne.faomaintenance.api.jooq.tables.Sites.SITES);
	}

	private Sites(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sites(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord> getPrimaryKey() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.SITE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.SITE_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.SitesRecord, ?>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.SITES__SITE_DEPT_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ccjmne.faomaintenance.api.jooq.tables.Sites as(java.lang.String alias) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Sites(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ccjmne.faomaintenance.api.jooq.tables.Sites rename(java.lang.String name) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Sites(name, null);
	}
}
