/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trainingtypes extends org.jooq.impl.TableImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> {

	private static final long serialVersionUID = 397244003;

	/**
	 * The reference instance of <code>public.trainingtypes</code>
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes TRAININGTYPES = new org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> getRecordType() {
		return org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord.class;
	}

	/**
	 * The column <code>public.trainingtypes.trty_pk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.Integer> TRTY_PK = createField("trty_pk", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.trainingtypes.trty_cert_fk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.Integer> TRTY_CERT_FK = createField("trty_cert_fk", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.trainingtypes.trty_validity</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.Integer> TRTY_VALIDITY = createField("trty_validity", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.trainingtypes.trty_name</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.String> TRTY_NAME = createField("trty_name", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * Create a <code>public.trainingtypes</code> table reference
	 */
	public Trainingtypes() {
		this("trainingtypes", null);
	}

	/**
	 * Create an aliased <code>public.trainingtypes</code> table reference
	 */
	public Trainingtypes(java.lang.String alias) {
		this(alias, org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes.TRAININGTYPES);
	}

	private Trainingtypes(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Trainingtypes(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, java.lang.Integer> getIdentity() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.IDENTITY_TRAININGTYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord> getPrimaryKey() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.TRTY_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.TRTY_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingtypesRecord, ?>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.TRAININGTYPES__TRTY_CERT_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes as(java.lang.String alias) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes rename(java.lang.String name) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Trainingtypes(name, null);
	}
}
