/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingsEmployees extends org.jooq.impl.TableImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> {

	private static final long serialVersionUID = 12936986;

	/**
	 * The reference instance of <code>public.trainings_employees</code>
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees TRAININGS_EMPLOYEES = new org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> getRecordType() {
		return org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord.class;
	}

	/**
	 * The column <code>public.trainings_employees.trem_pk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.Integer> TREM_PK = createField("trem_pk", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.trainings_employees.trem_trng_fk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.Integer> TREM_TRNG_FK = createField("trem_trng_fk", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.trainings_employees.trem_valid</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.Boolean> TREM_VALID = createField("trem_valid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.trainings_employees.trem_comment</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.String> TREM_COMMENT = createField("trem_comment", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>public.trainings_employees.trem_empl_fk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.String> TREM_EMPL_FK = createField("trem_empl_fk", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * Create a <code>public.trainings_employees</code> table reference
	 */
	public TrainingsEmployees() {
		this("trainings_employees", null);
	}

	/**
	 * Create an aliased <code>public.trainings_employees</code> table reference
	 */
	public TrainingsEmployees(java.lang.String alias) {
		this(alias, org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees.TRAININGS_EMPLOYEES);
	}

	private TrainingsEmployees(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> aliased) {
		this(alias, aliased, null);
	}

	private TrainingsEmployees(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, java.lang.Integer> getIdentity() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.IDENTITY_TRAININGS_EMPLOYEES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord> getPrimaryKey() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.TREM_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.TREM_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.ccjmne.faomaintenance.api.jooq.tables.records.TrainingsEmployeesRecord, ?>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.TRAININGS_EMPLOYEES__TREM_TRNG_FK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees as(java.lang.String alias) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees rename(java.lang.String name) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.TrainingsEmployees(name, null);
	}
}
