/**
 * This class is generated by jOOQ
 */
package org.ccjmne.faomaintenance.api.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Updates extends org.jooq.impl.TableImpl<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> {

	private static final long serialVersionUID = 367497109;

	/**
	 * The reference instance of <code>public.updates</code>
	 */
	public static final org.ccjmne.faomaintenance.api.jooq.tables.Updates UPDATES = new org.ccjmne.faomaintenance.api.jooq.tables.Updates();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> getRecordType() {
		return org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord.class;
	}

	/**
	 * The column <code>public.updates.updt_pk</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord, java.lang.Integer> UPDT_PK = createField("updt_pk", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.updates.updt_date</code>.
	 */
	public final org.jooq.TableField<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord, java.sql.Date> UPDT_DATE = createField("updt_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * Create a <code>public.updates</code> table reference
	 */
	public Updates() {
		this("updates", null);
	}

	/**
	 * Create an aliased <code>public.updates</code> table reference
	 */
	public Updates(java.lang.String alias) {
		this(alias, org.ccjmne.faomaintenance.api.jooq.tables.Updates.UPDATES);
	}

	private Updates(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Updates(java.lang.String alias, org.jooq.Table<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.ccjmne.faomaintenance.api.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord, java.lang.Integer> getIdentity() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.IDENTITY_UPDATES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord> getPrimaryKey() {
		return org.ccjmne.faomaintenance.api.jooq.Keys.UPDT_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.ccjmne.faomaintenance.api.jooq.tables.records.UpdatesRecord>>asList(org.ccjmne.faomaintenance.api.jooq.Keys.UPDT_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.ccjmne.faomaintenance.api.jooq.tables.Updates as(java.lang.String alias) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Updates(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.ccjmne.faomaintenance.api.jooq.tables.Updates rename(java.lang.String name) {
		return new org.ccjmne.faomaintenance.api.jooq.tables.Updates(name, null);
	}
}
