/**
 * This class is generated by jOOQ
 */
package asdf.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CertificatesRecord extends org.jooq.impl.UpdatableRecordImpl<asdf.tables.records.CertificatesRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = 634958833;

	/**
	 * Setter for <code>public.certificates.cert_pk</code>.
	 */
	public void setCertPk(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.certificates.cert_pk</code>.
	 */
	public java.lang.Integer getCertPk() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.certificates.cert_name</code>.
	 */
	public void setCertName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.certificates.cert_name</code>.
	 */
	public java.lang.String getCertName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.certificates.cert_target</code>.
	 */
	public void setCertTarget(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.certificates.cert_target</code>.
	 */
	public java.lang.Integer getCertTarget() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.certificates.cert_permanentonly</code>.
	 */
	public void setCertPermanentonly(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.certificates.cert_permanentonly</code>.
	 */
	public java.lang.Boolean getCertPermanentonly() {
		return (java.lang.Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return asdf.tables.Certificates.CERTIFICATES.CERT_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return asdf.tables.Certificates.CERTIFICATES.CERT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return asdf.tables.Certificates.CERTIFICATES.CERT_TARGET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return asdf.tables.Certificates.CERTIFICATES.CERT_PERMANENTONLY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getCertPk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCertName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCertTarget();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getCertPermanentonly();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CertificatesRecord value1(java.lang.Integer value) {
		setCertPk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CertificatesRecord value2(java.lang.String value) {
		setCertName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CertificatesRecord value3(java.lang.Integer value) {
		setCertTarget(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CertificatesRecord value4(java.lang.Boolean value) {
		setCertPermanentonly(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CertificatesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Boolean value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CertificatesRecord
	 */
	public CertificatesRecord() {
		super(asdf.tables.Certificates.CERTIFICATES);
	}

	/**
	 * Create a detached, initialised CertificatesRecord
	 */
	public CertificatesRecord(java.lang.Integer certPk, java.lang.String certName, java.lang.Integer certTarget, java.lang.Boolean certPermanentonly) {
		super(asdf.tables.Certificates.CERTIFICATES);

		setValue(0, certPk);
		setValue(1, certName);
		setValue(2, certTarget);
		setValue(3, certPermanentonly);
	}
}
