/**
 * This class is generated by jOOQ
 */
package asdf.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitesRecord extends org.jooq.impl.UpdatableRecordImpl<asdf.tables.records.SitesRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 2098059425;

	/**
	 * Setter for <code>public.sites.site_pk</code>.
	 */
	public void setSitePk(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.sites.site_pk</code>.
	 */
	public java.lang.String getSitePk() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.sites.site_name</code>.
	 */
	public void setSiteName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.sites.site_name</code>.
	 */
	public java.lang.String getSiteName() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return asdf.tables.Sites.SITES.SITE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return asdf.tables.Sites.SITES.SITE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSitePk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSiteName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord value1(java.lang.String value) {
		setSitePk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord value2(java.lang.String value) {
		setSiteName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SitesRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SitesRecord
	 */
	public SitesRecord() {
		super(asdf.tables.Sites.SITES);
	}

	/**
	 * Create a detached, initialised SitesRecord
	 */
	public SitesRecord(java.lang.String sitePk, java.lang.String siteName) {
		super(asdf.tables.Sites.SITES);

		setValue(0, sitePk);
		setValue(1, siteName);
	}
}
