/**
 * This class is generated by jOOQ
 */
package asdf.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdatesRecord extends org.jooq.impl.UpdatableRecordImpl<asdf.tables.records.UpdatesRecord> implements org.jooq.Record2<java.lang.Integer, java.sql.Date> {

	private static final long serialVersionUID = 1658413645;

	/**
	 * Setter for <code>public.updates.updt_pk</code>.
	 */
	public void setUpdtPk(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.updates.updt_pk</code>.
	 */
	public java.lang.Integer getUpdtPk() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.updates.updt_date</code>.
	 */
	public void setUpdtDate(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.updates.updt_date</code>.
	 */
	public java.sql.Date getUpdtDate() {
		return (java.sql.Date) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.sql.Date> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.sql.Date> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return asdf.tables.Updates.UPDATES.UPDT_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return asdf.tables.Updates.UPDATES.UPDT_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUpdtPk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getUpdtDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpdatesRecord value1(java.lang.Integer value) {
		setUpdtPk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpdatesRecord value2(java.sql.Date value) {
		setUpdtDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UpdatesRecord values(java.lang.Integer value1, java.sql.Date value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UpdatesRecord
	 */
	public UpdatesRecord() {
		super(asdf.tables.Updates.UPDATES);
	}

	/**
	 * Create a detached, initialised UpdatesRecord
	 */
	public UpdatesRecord(java.lang.Integer updtPk, java.sql.Date updtDate) {
		super(asdf.tables.Updates.UPDATES);

		setValue(0, updtPk);
		setValue(1, updtDate);
	}
}
