/**
 * This class is generated by jOOQ
 */
package asdf.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingsEmployeesRecord extends org.jooq.impl.UpdatableRecordImpl<asdf.tables.records.TrainingsEmployeesRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 2106116593;

	/**
	 * Setter for <code>public.trainings_employees.trem_pk</code>.
	 */
	public void setTremPk(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.trainings_employees.trem_pk</code>.
	 */
	public java.lang.Integer getTremPk() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.trainings_employees.trem_trng_fk</code>.
	 */
	public void setTremTrngFk(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.trainings_employees.trem_trng_fk</code>.
	 */
	public java.lang.Integer getTremTrngFk() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.trainings_employees.trem_valid</code>.
	 */
	public void setTremValid(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.trainings_employees.trem_valid</code>.
	 */
	public java.lang.Boolean getTremValid() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>public.trainings_employees.trem_comment</code>.
	 */
	public void setTremComment(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.trainings_employees.trem_comment</code>.
	 */
	public java.lang.String getTremComment() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.trainings_employees.trem_empl_fk</code>.
	 */
	public void setTremEmplFk(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.trainings_employees.trem_empl_fk</code>.
	 */
	public java.lang.String getTremEmplFk() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_TRNG_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_VALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES.TREM_EMPL_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTremPk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTremTrngFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getTremValid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTremComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTremEmplFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsEmployeesRecord value1(java.lang.Integer value) {
		setTremPk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsEmployeesRecord value2(java.lang.Integer value) {
		setTremTrngFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsEmployeesRecord value3(java.lang.Boolean value) {
		setTremValid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsEmployeesRecord value4(java.lang.String value) {
		setTremComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsEmployeesRecord value5(java.lang.String value) {
		setTremEmplFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingsEmployeesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Boolean value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrainingsEmployeesRecord
	 */
	public TrainingsEmployeesRecord() {
		super(asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES);
	}

	/**
	 * Create a detached, initialised TrainingsEmployeesRecord
	 */
	public TrainingsEmployeesRecord(java.lang.Integer tremPk, java.lang.Integer tremTrngFk, java.lang.Boolean tremValid, java.lang.String tremComment, java.lang.String tremEmplFk) {
		super(asdf.tables.TrainingsEmployees.TRAININGS_EMPLOYEES);

		setValue(0, tremPk);
		setValue(1, tremTrngFk);
		setValue(2, tremValid);
		setValue(3, tremComment);
		setValue(4, tremEmplFk);
	}
}
