/**
 * This class is generated by jOOQ
 */
package asdf.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainingtypesRecord extends org.jooq.impl.UpdatableRecordImpl<asdf.tables.records.TrainingtypesRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 409619217;

	/**
	 * Setter for <code>public.trainingtypes.trty_pk</code>.
	 */
	public void setTrtyPk(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.trainingtypes.trty_pk</code>.
	 */
	public java.lang.Integer getTrtyPk() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.trainingtypes.trty_cert_fk</code>.
	 */
	public void setTrtyCertFk(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.trainingtypes.trty_cert_fk</code>.
	 */
	public java.lang.Integer getTrtyCertFk() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.trainingtypes.trty_validity</code>.
	 */
	public void setTrtyValidity(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.trainingtypes.trty_validity</code>.
	 */
	public java.lang.Integer getTrtyValidity() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.trainingtypes.trty_name</code>.
	 */
	public void setTrtyName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.trainingtypes.trty_name</code>.
	 */
	public java.lang.String getTrtyName() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_CERT_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_VALIDITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return asdf.tables.Trainingtypes.TRAININGTYPES.TRTY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTrtyPk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTrtyCertFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTrtyValidity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTrtyName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingtypesRecord value1(java.lang.Integer value) {
		setTrtyPk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingtypesRecord value2(java.lang.Integer value) {
		setTrtyCertFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingtypesRecord value3(java.lang.Integer value) {
		setTrtyValidity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingtypesRecord value4(java.lang.String value) {
		setTrtyName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TrainingtypesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TrainingtypesRecord
	 */
	public TrainingtypesRecord() {
		super(asdf.tables.Trainingtypes.TRAININGTYPES);
	}

	/**
	 * Create a detached, initialised TrainingtypesRecord
	 */
	public TrainingtypesRecord(java.lang.Integer trtyPk, java.lang.Integer trtyCertFk, java.lang.Integer trtyValidity, java.lang.String trtyName) {
		super(asdf.tables.Trainingtypes.TRAININGTYPES);

		setValue(0, trtyPk);
		setValue(1, trtyCertFk);
		setValue(2, trtyValidity);
		setValue(3, trtyName);
	}
}
